name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'env'
      - uses: actions/checkout@v2
        with:
          repository: fingerprintjs/fingerprintjs-pro-cloudflare-worker
          ref: master
          path: worker
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Show files
        run: 'ls -lah'
      - name: Show env
        run: 'cat env/environment'
      - name: Cd to worker
        run: 'cd worker'
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}
          CF_ZONE_ID: ${{secrets.CF_ZONE_ID}}
          CF_ROUTE: ${{secrets.CF_ROUTE}}
